# https://hub.docker.com/_/nextcloud/
#
# --- plik nginx.conf:
# https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf

# --- fix do caldav:
# https://github.com/nextcloud/docker/issues/927

# --- cron, smb, imap 
# https://github.com/nextcloud/docker/tree/master/.examples/dockerfiles

# --- problem z logowaniem (trzeba odswiezyc przegladarke)
#
# https://help.nextcloud.com/t/30-sec-to-wait-before-login-since-update-10-0/2599/10
# https://help.nextcloud.com/t/nextcloud-login-issue-google-chrome/65958/3
#
# dzialaja oba rozwiazania: albo wpis overwrite, albo trusted proxy
#
#'overwrite.cli.url' => 'https://files.qkey.pro', 'overwritehost' => 'files.qkey.pro', 'overwriteprotocol' => 'https',
#
#'trusted_proxies' => array('192.168.1.100'),
#'trusted_proxies' => array('192.168.1.0/24'),


version: '2'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:fpm
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=
      - NEXTCLOUD_ADMIN_PASSWORD=
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.twojdoradca.nl
    restart: always

  web:
    image: nginx
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - nginx:/etc/nginx
    volumes_from:
      - app
    restart: always
    environment:
      - VIRTUAL_HOST=nextcloud.twojdoradca.nl

#volumes:
#  nextcloud:
#  db:
